name: petwise
description: An application to help find missing animals.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  git_hooks: 0.1.3-nullsafety.0

flutter:
  generate: true
  uses-material-design: true